config/routes.rb
Rails.application.routes.draw do
  get "/", to: "pages#home", as: "root"
  get "about", to: "pages#about"
  get "projects", to: "pages#projects"
  get "contact", to: "pages#contact"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def home
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
  end

  def home
  end

  def projects
  end

  def conact
  end

  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Noah Leal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= controller_name %> <%= action_name %>" >

    <%= yield %>

  </body>
</html>

app/views/pages/about.html.erb
<div class="about-background">
  <div class="vertical-wrapper text-center">
    <div class="container windows-background">
      <div class="row about-row">
        <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
          <br>
          <h3>Who is Noah Leal?</h3>
          <p>I am a Ruby on Rails software engineer with a multidiciplinary background. I studied fullstack development at Le Wagon in Berlin and graduated with a love for backend engineering. No, I didn't learn frontend development in the 90's- I just like brutalist web design. I love spending time with my friends, reading good books, spending time in graveyards, and good humor.</p>
          <h3>What do I know?</h3>
          I studied liberal arts at <a href="https://www.sjc.edu/about"> St. John's College </a> in Santa Fe, New Mexico. St. John's is a very unusual, but very incredible place to study. The school offers no choice in what you study, so each student follows the prescribed classics program. At best, going through the program gives you a history of Western thinking in many forms, and fosters the ability to think well and ask good questions.  Among other things, we studied Ancient Greek, astronomy, opera, poetry, linguistics, Euclidean Geometry, Calculus, biology and electrodynamics. You can read my thesis on Heideggarian aesthetics <a href="https://www.dropbox.com/s/g81cva6b1myiixv/Undergraduate%20Thesis.pdf?dl=0">here</a>.
          <h3>Why should you hire me?</h3>
          I genuinely love coding, I live to learn, and I get a lot of motivation from working with other people. What can I say? I play well with others. I take things slow, I unpack problems with my teammates and I articulate my own questions and confusions coherently and understandably. We learn by being honest, and I'm working my way from irony to sincerity. Check out <a href="https://www.dropbox.com/s/agcivwyledard8w/Noah%20Leal%20CV.pdf?dl=0">my cv</a> or <%= link_to "contact me", contact_path%>.
        </div>
      </div>
    </div>
    <%= link_to "Back", root_path  %>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="video-background">
    <div class="video-foreground">
      <iframe src="https://www.youtube.com/embed/WpKgiqmXM30?controls=0&showinfo=0&rel=0&autoplay=1&loop=1&playlist=W0LHTWG-UmQ" frameborder="0" allowfullscreen></iframe>
    </div>
</div>
<div class="contact-background">
  <div class="vertical-wrapper text-center">
    <div class="container">
      <div class="row about-row">
        <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
          <%= image_tag 'aimprofile.png', :usemap => "#image-map" %>
      </div>
    </div>
    <%= link_to "Back", root_path  %>
  </div>
</div>



<map name="image-map">
    <area target="_blank" alt="LinkedIn" title="LinkedIn" href="https://www.linkedin.com/in/noahleal/" coords="183,331,240,384" shape="rect">
    <area target="_blank" alt="github" title="github" href="https://github.com/noahleal" coords="183,223,240,278" shape="rect">
    <area target="" alt="email" title="email" href="mailto:noahleal@me.com" coords="188,452,239,489" shape="rect">
</map>

app/views/pages/home.html.erb
<div class= "home-body">
  <p><%= image_tag 'welcome-tto-my-site1.gif', :class => "welcome-gif" %></p>

  <h1>NOAH LEAL: "JUNIOR" WEB DEVELOPER</h1>
      <ul>
        <li><%= link_to "About", about_path%></li>
        <li><%= link_to "Projects", projects_path%></li>
        <li><%= link_to "Contact", contact_path%></li>
  </ul>

</div>

app/views/pages/projects.html.erb
<div class="projects-background">
  <div class="vertical-wrapper text-center">
    <div class="container mac-background">
      <div class="row about-row">
        <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
          <br>
          <h3 class="logos"><a target="_blank" href="http://www.artroom.fun"><%= image_tag 'Artroom.png'%> </a></h3>
          <p>Artroom is a contemporary art discovery application built with Ruby on Rails. I worked with a group of four people using Git and pair programming to colaborate. Our process included morning task delegation and progress reports and iterative development through branch
          pull-requests and code-reviews. I focused mainly on frontend
          design and UX; Active Admin; model generation; a complex
          index method; bug hunting and squashing; content writing;
          seed generation and art research. Though, being such a small
          team, I took on various daily tasks as they arose including
          constant debugging for team members and code-review. <a target="_blank" href="https://github.com/GLTaylor/Artroom">repo</a> </p>
          <h3 class="logos"><a target="_blank" href="https://jolt-171.herokuapp.com/"> <%= image_tag 'Jolt.png' %> </a> </h3>
          Jolt is an AirBNB clone that served as a preliminary project to
          prepare for Artroom. Built using Ruby on Rails, ActiveRecord,
          SASS, PostgreSQL, pg_search, cloudinary, Heroku, pry-byebug and Figma. <a target="_blank" href="https://github.com/GLTaylor/JOLT">repo</a>
          <h3><a href="http://www.afea.co.uk/">AFEA</a></h3>
          My first solo project after Le Wagon, designed using
          WordPress at the client's request. I am responsible for the site
          from the ground up including private server management. I
          developed the site on my localhost and migrated to a server
          owned by the client. AFEA is an organization, so my duties
          include managing the design requests of and reporting to
          multiple people.
        </div>
      </div>
    </div>
    <%= link_to "Back", root_path  %>
  </div>
</div>

app/views/shared/_navbar.html.erb
_navbar.html.erb